spring.application.name=auth-server
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
rsa.private-key-value=${RSA_PRIVATE_KEY_VALUE}
rsa.public-key-value=${RSA_PUBLIC_KEY_VALUE}
admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}
